spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.47.36/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: XXXXXXXXX


logging:
  level:
    root: warn
    com.xsh: info
  file:
    path: log/blog-pro.log

server:
  port: 8080
