#开发环境配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.17:3306/jason_chan_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 19650223.Chen>

  redis:
    host: 192.168.43.17
    password: 19650223.Chen>
    port: 6379
    connect-timeout: 6000 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 2
        max-idle: 10 # 连接池中的最大空闲连接

logging:
  level:
    root: info #设置全局日志级别，此处默认为info,生产环境可设置为更高级别的warn
    com.jasonc.blog: debug #指定对应目录的日志级别，在此目录内的日志级别为debug

  file:
    name: log-dev/blog-dev.log

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 默认评论头像
comment:
  avatar: /images/userAvatar.jpg

#qq登录管理员id
admin:
  openid: C4C8ABCDDD87236013418B6DFC0F92B4

##设置cookie的生命周期为十天，单位秒。 60*60*24*10
cookie:
  time: 864000